add support download

diff --git a/usr/lib/enigma2/python/Plugins/Extensions/tvManager/auto b/usr/lib/enigma2/python/Plugins/Extensions/tvManager/auto
--- a/usr/lib/enigma2/python/Plugins/Extensions/tvManager/auto
+++ b/usr/lib/enigma2/python/Plugins/Extensions/tvManager/auto
@@ -14,12 +14,41 @@ softcam="https://raw.githubusercontent.com/pablitodrito/prova-pablito/master/Sof
 #autokeysbylokum="http://www.lokumsat.esy.es/CaMs-EmU/autokeysbylokum.sh"
 # SoftcamKeys="http://sat-linux.com/addons/SoftCam.Key"
 # Constant="http://sat-linux.com/addons/constant.cw"
-
+KeysUpdater="http://levi45.spdns.eu/Addons/Multicam/Keys_Updater.sh"
+SoftcamKeys="http://levi45.spdns.eu/Addons/SoftCam.Key"
+Constantcw="http://levi45.spdns.eu/Addons/constant.cw"
+OscamKeys="http://levi45.spdns.eu/Addons/oscam.keys"
+Oscamconstantcw="http://levi45.spdns.eu/Addons/oscam.constant.cw"
 echo ""
 echo ""
-echo "Downloading ${softcam}"
-#wget ${softcam} -O /etc/tuxbox/config/SoftCam.Key || echo "Error: Couldn't connect to ${softcam}"
-wget ${softcam} -O /usr/keys/SoftCam.Key || echo "Error: Couldn't connect to ${softcam}"
+# echo "Downloading ${KeysUpdater}"
+# wget ${KeysUpdater} -O /usr/lib/enigma2/python/Plugins/Extensions/Manager/emu/Keys_Updater.sh || echo "Error: Couldn't connect to ${KeysUpdater}"
+# echo ""
+# chmod 775 /usr/lib/enigma2/python/Plugins/Extensions/Manager/emu/Keys_Updater.sh
+# echo ""
+echo "Downloading ${SoftcamKeys}"
+wget ${SoftcamKeys} -O /usr/keys/SoftCam.Key || echo "Error: Couldn't connect to ${SoftcamKeys}"
+echo ""
+echo "Downloading ${SoftcamKeys}"
+wget ${SoftcamKeys} -O /etc/tuxbox/config/SoftCam.Key || echo "Error: Couldn't connect to ${SoftcamKeys}"
+echo ""
+echo "Downloading ${Constantcw}"
+wget ${Constantcw} -O /etc/tuxbox/config/constant.cw || echo "Error: Couldn't connect to ${Constantcw}"
+echo ""
+echo "Downloading ${Constantcw}"
+wget ${Constantcw} -O /usr/keys/constant.cw || echo "Error: Couldn't connect to ${Constantcw}"
+echo ""
+echo "Downloading ${OscamKeys}"
+wget ${OscamKeys} -O /etc/tuxbox/config/oscam.keys || echo "Error: Couldn't connect to ${OscamKeys}"
+echo ""
+echo "Downloading ${Oscamconstantcw}"
+wget ${Oscamconstantcw} -O /etc/tuxbox/config/oscam.constant.cw || echo "Error: Couldn't connect to ${Oscamconstantcw}"
+echo ""
+echo ""
+echo ""
+# echo "Downloading ${softcam}"
+# # wget ${softcam} -O /etc/tuxbox/config/SoftCam.Key || echo "Error: Couldn't connect to ${softcam}"
+# wget ${softcam} -O /usr/keys/SoftCam.Key || echo "Error: Couldn't connect to ${softcam}"
 echo ""
 
 echo ""
